name: Deploy to render

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build docker image
              run: docker build -t ask-my-pdf:latest .

            - name: Deploy trigger
              run: curl -X POST https://api.render.com/deploy/srv-d0uubo7diees73dqdkp0?key=$RENDER_API_KEY
              env: 
                RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}